# Generated by Django 3.0.6 on 2020-05-30 10:52

import bugz.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField(blank=True)),
                ("color", bugz.models.ColorField(default="#ffffff", max_length=9)),
            ],
            options={"ordering": ("name",),},
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=280)),
                ("description", models.TextField(blank=True)),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now)),
                ("open", models.BooleanField(db_index=True, default=True)),
                ("locked", models.BooleanField(db_index=True, default=False)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "authored_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "blocked_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="_ticket_blocked_by_+",
                        to="bugz.Ticket",
                    ),
                ),
                (
                    "dupe_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dupes",
                        to="bugz.Ticket",
                    ),
                ),
                ("labels", models.ManyToManyField(blank=True, to="bugz.Label")),
            ],
            options={"ordering": ("-created_on",),},
        ),
        migrations.CreateModel(
            name="TicketUpdate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "authored_on",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("old_value", models.TextField(blank=True)),
                ("comment", models.TextField(blank=True)),
                (
                    "authored_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_ticket_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="bugz.Ticket",
                    ),
                ),
            ],
            options={"ordering": ["authored_on"],},
        ),
    ]
